name: pggan
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.5.7
  - flake8=3.9.2
  - pip=21.1.3
  - python=3.9.5
  - opencv=4.5.3
  - pip:
      - pyyaml==5.4.1
      - torch==1.9.0
      - numpy==1.21.2